[build]
  command = "npx nx build invoicely-frontend"
  publish = "apps/invoicely-frontend/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    disableServerFunctions = true
