[build]
  command = "npx nx build web"
  publish = "dist/apps/web/.next"
  functions = "dist/apps/web/.netlify/functions"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"
