export enum GstSlab {
  ZERO = 0,
  FIVE = 5,
  TWELVE = 12,
  EIGHTEEN = 18,
  TWENTY_EIGHT = 28,
}

export const GST_SLABS: GstSlab[] = [
  GstSlab.ZERO,
  GstSlab.FIVE,
  GstSlab.TWELVE,
  GstSlab.EIGHTEEN,
  GstSlab.TWENTY_EIGHT,
];

// GST Unique Quantity Codes (UQC) accepted on GST returns and e-way bills
export enum ProductUnit {
  BAGS = 'BAG',
  BALE = 'BAL',
  BUNDLES = 'BDL',
  BUCKLES = 'BKL',
  BILLIONS_OF_UNITS = 'BOU',
  BOX = 'BOX',
  BOTTLES = 'BTL',
  BUNCHES = 'BUN',
  CANS = 'CAN',
  CUBIC_METERS = 'CBM',
  CUBIC_CENTIMETERS = 'CCM',
  CENTIMETERS = 'CMS',
  CARTONS = 'CTN',
  DOZENS = 'DOZ',
  DRUMS = 'DRM',
  GREAT_GROSS = 'GGK',
  GRAMS = 'GMS',
  GROSS = 'GRS',
  GROSS_YARDS = 'GYD',
  KILOGRAMS = 'KGS',
  KILOLITRE = 'KLR',
  KILOMETRE = 'KME',
  LITRES = 'LTR',
  MILLILITRE = 'MLT',
  METERS = 'MTR',
  METRIC_TON = 'MTS',
  NUMBERS = 'NOS',
  PACKS = 'PAC',
  PIECES = 'PCS',
  PAIRS = 'PRS',
  QUINTAL = 'QTL',
  ROLLS = 'ROL',
  SETS = 'SET',
  SQUARE_FEET = 'SQF',
  SQUARE_METERS = 'SQM',
  SQUARE_YARDS = 'SQY',
  TABLETS = 'TBS',
  TEN_GROSS = 'TGM',
  THOUSANDS = 'THD',
  TONNES = 'TON',
  TUBES = 'TUB',
  US_GALLONS = 'UGS',
  UNITS = 'UNT',
  YARDS = 'YDS',
  OTHERS = 'OTH',
}

export const PRODUCT_UNITS: ProductUnit[] = [
  ProductUnit.BAGS,
  ProductUnit.BALE,
  ProductUnit.BUNDLES,
  ProductUnit.BUCKLES,
  ProductUnit.BILLIONS_OF_UNITS,
  ProductUnit.BOX,
  ProductUnit.BOTTLES,
  ProductUnit.BUNCHES,
  ProductUnit.CANS,
  ProductUnit.CUBIC_METERS,
  ProductUnit.CUBIC_CENTIMETERS,
  ProductUnit.CENTIMETERS,
  ProductUnit.CARTONS,
  ProductUnit.DOZENS,
  ProductUnit.DRUMS,
  ProductUnit.GREAT_GROSS,
  ProductUnit.GRAMS,
  ProductUnit.GROSS,
  ProductUnit.GROSS_YARDS,
  ProductUnit.KILOGRAMS,
  ProductUnit.KILOLITRE,
  ProductUnit.KILOMETRE,
  ProductUnit.LITRES,
  ProductUnit.MILLILITRE,
  ProductUnit.METERS,
  ProductUnit.METRIC_TON,
  ProductUnit.NUMBERS,
  ProductUnit.PACKS,
  ProductUnit.PIECES,
  ProductUnit.PAIRS,
  ProductUnit.QUINTAL,
  ProductUnit.ROLLS,
  ProductUnit.SETS,
  ProductUnit.SQUARE_FEET,
  ProductUnit.SQUARE_METERS,
  ProductUnit.SQUARE_YARDS,
  ProductUnit.TABLETS,
  ProductUnit.TEN_GROSS,
  ProductUnit.THOUSANDS,
  ProductUnit.TONNES,
  ProductUnit.TUBES,
  ProductUnit.US_GALLONS,
  ProductUnit.UNITS,
  ProductUnit.YARDS,
  ProductUnit.OTHERS,
];

export const PRODUCT_UNIT_LABELS: Record<ProductUnit, string> = {
  [ProductUnit.BAGS]: 'Bags',
  [ProductUnit.BALE]: 'Bale',
  [ProductUnit.BUNDLES]: 'Bundles',
  [ProductUnit.BUCKLES]: 'Buckles',
  [ProductUnit.BILLIONS_OF_UNITS]: 'Billions of Units',
  [ProductUnit.BOX]: 'Box',
  [ProductUnit.BOTTLES]: 'Bottles',
  [ProductUnit.BUNCHES]: 'Bunches',
  [ProductUnit.CANS]: 'Cans',
  [ProductUnit.CUBIC_METERS]: 'Cubic Meters',
  [ProductUnit.CUBIC_CENTIMETERS]: 'Cubic Centimeters',
  [ProductUnit.CENTIMETERS]: 'Centimeters',
  [ProductUnit.CARTONS]: 'Cartons',
  [ProductUnit.DOZENS]: 'Dozens',
  [ProductUnit.DRUMS]: 'Drums',
  [ProductUnit.GREAT_GROSS]: 'Great Gross',
  [ProductUnit.GRAMS]: 'Grams',
  [ProductUnit.GROSS]: 'Gross',
  [ProductUnit.GROSS_YARDS]: 'Gross Yards',
  [ProductUnit.KILOGRAMS]: 'Kilograms',
  [ProductUnit.KILOLITRE]: 'Kilolitre',
  [ProductUnit.KILOMETRE]: 'Kilometre',
  [ProductUnit.LITRES]: 'Litres',
  [ProductUnit.MILLILITRE]: 'Millilitre',
  [ProductUnit.METERS]: 'Meters',
  [ProductUnit.METRIC_TON]: 'Metric Ton',
  [ProductUnit.NUMBERS]: 'Numbers',
  [ProductUnit.PACKS]: 'Packs',
  [ProductUnit.PIECES]: 'Pieces',
  [ProductUnit.PAIRS]: 'Pairs',
  [ProductUnit.QUINTAL]: 'Quintal',
  [ProductUnit.ROLLS]: 'Rolls',
  [ProductUnit.SETS]: 'Sets',
  [ProductUnit.SQUARE_FEET]: 'Square Feet',
  [ProductUnit.SQUARE_METERS]: 'Square Meters',
  [ProductUnit.SQUARE_YARDS]: 'Square Yards',
  [ProductUnit.TABLETS]: 'Tablets',
  [ProductUnit.TEN_GROSS]: 'Ten Gross',
  [ProductUnit.THOUSANDS]: 'Thousands',
  [ProductUnit.TONNES]: 'Tonnes',
  [ProductUnit.TUBES]: 'Tubes',
  [ProductUnit.US_GALLONS]: 'US Gallons',
  [ProductUnit.UNITS]: 'Units',
  [ProductUnit.YARDS]: 'Yards',
  [ProductUnit.OTHERS]: 'Others',
};
