export enum IndianState {
  ANDAMAN_AND_NICOBAR_ISLANDS = 'Andaman and Nicobar Islands',
  ANDHRA_PRADESH = 'Andhra Pradesh',
  ARUNACHAL_PRADESH = 'Arunachal Pradesh',
  ASSAM = 'Assam',
  BIHAR = 'Bihar',
  CHANDIGARH = 'Chandigarh',
  CHHATTISGARH = 'Chhattisgarh',
  DADRA_NAGAR_HAVELI_DAMAN_DIU = 'Dadra and Nagar Haveli and Daman and Diu',
  DELHI = 'Delhi',
  GOA = 'Goa',
  GUJARAT = 'Gujarat',
  HARYANA = 'Haryana',
  HIMACHAL_PRADESH = 'Himachal Pradesh',
  JAMMU_AND_KASHMIR = 'Jammu and Kashmir',
  JHARKHAND = 'Jharkhand',
  KARNATAKA = 'Karnataka',
  KERALA = 'Kerala',
  LADAKH = 'Ladakh',
  LAKSHADWEEP = 'Lakshadweep',
  MADHYA_PRADESH = 'Madhya Pradesh',
  MAHARASHTRA = 'Maharashtra',
  MANIPUR = 'Manipur',
  MEGHALAYA = 'Meghalaya',
  MIZORAM = 'Mizoram',
  NAGALAND = 'Nagaland',
  ODISHA = 'Odisha',
  PUDUCHERRY = 'Puducherry',
  PUNJAB = 'Punjab',
  RAJASTHAN = 'Rajasthan',
  SIKKIM = 'Sikkim',
  TAMIL_NADU = 'Tamil Nadu',
  TELANGANA = 'Telangana',
  TRIPURA = 'Tripura',
  UTTAR_PRADESH = 'Uttar Pradesh',
  UTTARAKHAND = 'Uttarakhand',
  WEST_BENGAL = 'West Bengal',
}

export const INDIAN_STATES: IndianState[] = [
  IndianState.ANDAMAN_AND_NICOBAR_ISLANDS,
  IndianState.ANDHRA_PRADESH,
  IndianState.ARUNACHAL_PRADESH,
  IndianState.ASSAM,
  IndianState.BIHAR,
  IndianState.CHANDIGARH,
  IndianState.CHHATTISGARH,
  IndianState.DADRA_NAGAR_HAVELI_DAMAN_DIU,
  IndianState.DELHI,
  IndianState.GOA,
  IndianState.GUJARAT,
  IndianState.HARYANA,
  IndianState.HIMACHAL_PRADESH,
  IndianState.JAMMU_AND_KASHMIR,
  IndianState.JHARKHAND,
  IndianState.KARNATAKA,
  IndianState.KERALA,
  IndianState.LADAKH,
  IndianState.LAKSHADWEEP,
  IndianState.MADHYA_PRADESH,
  IndianState.MAHARASHTRA,
  IndianState.MANIPUR,
  IndianState.MEGHALAYA,
  IndianState.MIZORAM,
  IndianState.NAGALAND,
  IndianState.ODISHA,
  IndianState.PUDUCHERRY,
  IndianState.PUNJAB,
  IndianState.RAJASTHAN,
  IndianState.SIKKIM,
  IndianState.TAMIL_NADU,
  IndianState.TELANGANA,
  IndianState.TRIPURA,
  IndianState.UTTAR_PRADESH,
  IndianState.UTTARAKHAND,
  IndianState.WEST_BENGAL,
];

export const GST_STATE_CODES: Record<string, IndianState> = {
  '01': IndianState.JAMMU_AND_KASHMIR,
  '02': IndianState.HIMACHAL_PRADESH,
  '03': IndianState.PUNJAB,
  '04': IndianState.CHANDIGARH,
  '05': IndianState.UTTARAKHAND,
  '06': IndianState.HARYANA,
  '07': IndianState.DELHI,
  '08': IndianState.RAJASTHAN,
  '09': IndianState.UTTAR_PRADESH,
  '10': IndianState.BIHAR,
  '11': IndianState.SIKKIM,
  '12': IndianState.ARUNACHAL_PRADESH,
  '13': IndianState.NAGALAND,
  '14': IndianState.MANIPUR,
  '15': IndianState.MIZORAM,
  '16': IndianState.TRIPURA,
  '17': IndianState.MEGHALAYA,
  '18': IndianState.ASSAM,
  '19': IndianState.WEST_BENGAL,
  '20': IndianState.JHARKHAND,
  '21': IndianState.ODISHA,
  '22': IndianState.CHHATTISGARH,
  '23': IndianState.MADHYA_PRADESH,
  '24': IndianState.GUJARAT,
  '25': IndianState.DADRA_NAGAR_HAVELI_DAMAN_DIU,
  '26': IndianState.DADRA_NAGAR_HAVELI_DAMAN_DIU,
  '27': IndianState.MAHARASHTRA,
  '28': IndianState.ANDHRA_PRADESH,
  '29': IndianState.KARNATAKA,
  '30': IndianState.GOA,
  '31': IndianState.LAKSHADWEEP,
  '32': IndianState.KERALA,
  '33': IndianState.TAMIL_NADU,
  '34': IndianState.PUDUCHERRY,
  '35': IndianState.ANDAMAN_AND_NICOBAR_ISLANDS,
  '36': IndianState.TELANGANA,
  '37': IndianState.ANDHRA_PRADESH,
  '38': IndianState.LADAKH,
};
